# TODO: replace `image: localhost/*` images with actual image paths once they
# are published to CR.

services:
  postgres:
    image: pgvector/pgvector:pg18-trixie
    container_name: carmen-postgres
    env_file:
      - env/.env.postgres
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  rustfs:
    image: rustfs/rustfs:latest
    container_name: carmen-rustfs
    ports:
      - 9001:9001  # Web console
    env_file:
      - env/.env.rustfs
    restart: unless-stopped
    volumes:
      - rustfs_data:/data/rustfs

  migrations:
    image: localhost/carmen-migrations:latest
    container_name: carmen-migrations
    env_file:
      - env/.env.migrations
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy

  api:
    image: localhost/carmen-api:latest
    container_name: carmen-api
    env_file:
      - env/.env.api
    ports:
      - 5124:5124
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      rustfs:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    volumes:
      - fastembed_cache:/app/.fastembed_cache

  extractor:
    image: localhost/carmen-extractor:latest
    container_name: carmen-extractor
    env_file:
      - env/.env.extractor
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      rustfs:
        condition: service_started
      migrations:
        condition: service_completed_successfully

  indexer:
    image: localhost/carmen-indexer:latest
    container_name: carmen-indexer
    env_file:
      - env/.env.indexer
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      rustfs:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    volumes:
      - fastembed_cache:/app/.fastembed_cache


volumes:
  pg_data:
  rustfs_data:
  fastembed_cache:
