services:
  postgres:
    image: pgvector/pgvector:pg18-trixie
    container_name: carmen-postgres
    env_file:
      - env/.env.postgres
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql

  migrations:
    image: localhost/carmen-migrations:latest
    container_name: carmen-migrations
    env_file:
      - env/.env.migrations
    restart: unless-stopped

  indexer:
    image: localhost/carmen-indexer:latest
    container_name: carmen-indexer
    env_file:
      - env/.env.indexer
    restart: unless-stopped
    depends_on:
      migrations:
        condition: service_completed_successfully

  search:
    image: localhost/carmen-search:latest
    container_name: carmen-search
    env_file:
      - env/.env.search
    ports:
      - 5124:5124
    restart: unless-stopped
    depends_on:
      migrations:
        condition: service_completed_successfully


volumes:
  pg_data:
