services:
  s3:
    image: rustfs/rustfs:latest
    container_name: s3
    environment:
      RUSTFS_ADDRESS: :9000
      RUSTFS_CONSOLE_ADDRESS: :9001
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_VOLUMES: /data/rustfs
    env_file:
      # Contains RUSTFS_ACCESS_KEY and RUSTFS_SECRET_KEY
      - .env.s3
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - s3_data:/data/rustfs

  postgres:
    image: pgvector/pgvector:pg18-trixie
    container_name: postgres
    environment:
      POSTGRES_DB: carmen
    env_file:
      # Contains POSTGRES_USER and POSTGRES_PASSWORD
      - .env.postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql

  kafka-controller:
    image: apache/kafka:latest
    container_name: kafka-controller
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 1000
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN

  kafka-broker:
    image: apache/kafka:latest
    container_name: kafka-broker
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 1000
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
    depends_on:
      - kafka-controller

  embedding:
    build:
      context: ./embedding
      args:
        # Should match environment variables below.
        SENTENCE_TRANSFORMERS_HOME: /opt/sentence-transformers
        SENTENCE_TRANSFORMERS_MODEL: sentence-transformers/static-retrieval-mrl-en-v1
    container_name: embedding
    environment:
      CARMEN_EMBEDDING_KAFKA_URI: kafka-broker:9092
      CARMEN_EMBEDDING_KAFKA_CONSUMER_GROUP: embedding-consumer-group
      CARMEN_EMBEDDING_KAFKA_TOPIC_CHUNKS_QUEUE: chunks.queue
      CARMEN_EMBEDDING_KAFKA_TOPIC_CHUNKS_READY: chunks.ready
      CARMEN_EMBEDDING_SENTENCE_TRANSFORMERS_HOME: /opt/sentence-transformers
      CARMEN_EMBEDDING_SENTENCE_TRANSFORMERS_MODEL: sentence-transformers/static-retrieval-mrl-en-v1
    depends_on:
      - kafka-broker

  extractor:
    build:
      context: ./extractor
    container_name: extractor
    environment:
      CARMEN_EXTRACTOR_LOG: warn,extractor=info
      CARMEN_EXTRACTOR_S3_ENDPOINT: http://s3:9000
      CARMEN_EXTRACTOR_S3_REGION: eu-central-1
      CARMEN_EXTRACTOR_S3_BUCKET: carmen-tmp-bucket
      CARMEN_EXTRACTOR_KAFKA_URI: kafka-broker:9092
      CARMEN_EXTRACTOR_KAFKA_CONSUMER_GROUP: extractor-consumer-group
      CARMEN_EXTRACTOR_KAFKA_TOPIC_DOCUMENTS_QUEUE: documents.queue
      CARMEN_EXTRACTOR_KAFKA_TOPIC_CHUNKS_QUEUE: chunks.queue
    env_file:
      # Contains CARMEN_EXTRACTOR_S3_ACCESS_KEY and
      # CARMEN_EXTRACTOR_S3_SECRET_KEY 
      - .env.extractor
    depends_on:
      - kafka-broker
      - s3

volumes:
  s3_data:
  pg_data:
