FROM golang:1.26-alpine as builder

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

WORKDIR /app

# Cache dependencies.
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN ls
RUN go tool swag init -o swagger -g doc.go -d ./pkg/controller,./pkg/dto
RUN go build -o /app/search -trimpath -ldflags="-s -w" ./cmd/search


FROM gcr.io/distroless/base-debian12 as runtime

COPY --from=builder /app /app

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/app/search"]
