FROM python:3.12-slim as build

COPY --from=ghcr.io/astral-sh/uv:0.10.6 /uv /uvx /bin/
WORKDIR /app

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy

COPY uv.lock pyproject.toml ./
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --no-install-project --no-dev

COPY src src
COPY scripts scripts
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev


FROM python:3.12-slim AS runtime
ENV PATH="/app/.venv/bin:$PATH"

ARG USER=embedding
ARG GROUP=embedding

RUN groupadd "$GROUP" && \
    useradd -g "$GROUP" -m -d /app "$USER"

WORKDIR /app
COPY --from=build --chown="$USER:$GROUP" /app .

# Prepare sentence transformer model.
ARG SENTENCE_TRANSFORMERS_HOME=/opt/sentence-transformers
ARG SENTENCE_TRANSFORMERS_MODELS=""

RUN mkdir -p "$SENTENCE_TRANSFORMERS_HOME" && \
    chown "$USER:$GROUP" "$SENTENCE_TRANSFORMERS_HOME"

RUN python3 /app/scripts/prepare_model.py

USER "$USER"


ENTRYPOINT ["python3", "/app/src/main.py"]
